RotsmellCave_B1F_Text_AnotherTeamRocketMember::
    .string "{PLAY_BGM}{MUS_ENCOUNTER_ARTIFACT}Oh, another TEAM ROCKET member?\n"
    .string "Huh? Before you, a loser came and\l"
    .string "lost. Fwahhaha! Try if you dare.\l"
    .string "You shall not get the artifact…\l"
    .string "ARTIFACT OF ROTSMELL cannot be\l"
    .string "yours!\p"
    .string "Now… Give it a try, as you will\n"
    .string "regret for this.$"
