SecretPath_South_Text_CannotWanderInGrass::
    .string "Without POKéMON, I can't walk in\n"
    .string "the tall grass.$"

SecretPath_South_Text_CannotLeave::
    .string "I need to get back to the base!$"

SecretPath_South_Text_ThePoliceIsHere::
    .string "The police is here!$"

SecretPath_South_Text_RivalIntroduction::
    .string "[orange_fr]?????: [blue_fr]Oh, welcome! Do you have\nany POKéMON?\l... ... ... ... ... ... ... ...\l... ... ... ... ... ... ... ...\lMe neither. But, that's okay. Near\lhere, there is a POKéMON LAB.\lAnyway, my name is [rival]! Meet\lme at the entrance of PALLET TOWN!\lWe can steal some POKéMON there."