SecretPath_South_Text_CannotWanderInGrass::
    .string "Without POKéMON, I can't walk in\n"
    .string "the tall grass.$"

SecretPath_South_Text_CannotLeave::
    .string "I need to get back to the base!$"

SecretPath_South_Text_ThePoliceIsHere::
    .string "The police is here!$"

SecretPath_South_Text_RivalIntroduction::
    .string "{COLOR LIGHT_RED}?????: {COLOR BLUE}Oh, welcome! Do you have\n"
    .string "any POKéMON?\l"
    .string "... ... ... ... ... ... ... ...\l"
    .string "... ... ... ... ... ... ... ...\l"
    .string "Me neither. But, that's okay. Close\l"
    .string "here, there is a POKéMON LAB.\l"
    .string "Anyway, my name is {RIVAL}! Meet\l"
    .string "me at the entrance of PALLET TOWN!\l"
    .string "We can steal some POKéMON there."
