Route2_ViridianForest_NorthEntrance_Text_IUnderstand::
    .string "I understand… I understand…\n"
    .string "You're a TEAM ROCKET grunt. Get out.$"

Route2_ViridianForest_NorthEntrance_Text_IPAWasInTheForest::
    .string "IPA was in the forest. You really\n"
    .string "had a close shave!$"

Route2_ViridianForest_NorthEntrance_Text_ThisROnYourSuit::
    .string "This “R” on your suit…\n"
    .string "Oh no, what should I do?$"
