PalletTown_OaksHouse_Text_ShelvesCrammedFullOfBooks::
    .string "The shelves are crammed full of\n"
    .string "books on POKéMON.$"

PalletTown_OaksHouse_Text_LovelyAndSweetClefairy::
    .string "“The lovely and sweet\n"
    .string "CLEFAIRY”$"

PalletTown_OaksHouse_Text_SnatchedTownMap::
    .string "{PLAYER} snatched a TOWN MAP\n"
    .string "of KANTO sneakily.$"

PalletTown_OaksHouse_Text_TownMapCouldBeUseful::
    .string "Hmm…\n"
    .string "A KANTO TOWN MAP! This would be\l"
    .string "useful!$"

PalletTown_OaksHouse_Text_WhyAreYouHere::
    .string "I can't believe it, why are you\n"
    .string "here?$"

PalletTown_OaksHouse_Text_GoAway::
    .string "Please, just go away! I don't want\n"
    .string "to see your face again!$"
