gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Black::
    .string "BLACK$"

gNameChoice_Kirk::
    .string "KIRK$"

gNameChoice_Syd::
    .string "SYD$"

gNameChoice_Adam::
    .string "ADAM$"

gNameChoice_Axl::
    .string "AXL$"

gNameChoice_Cash::
    .string "CASH$"

gNameChoice_Chad::
    .string "CHAD$"

gNameChoice_Damon::
    .string "DAMON$"

gNameChoice_David::
    .string "DAVID$"

gNameChoice_Doug::
    .string "DOUG$"

gNameChoice_Eric::
    .string "ERIC$"

gNameChoice_Frank::
    .string "FRANK$"

gNameChoice_Harry::
    .string "HARRY$"

gNameChoice_Ike::
    .string "IKE$"

gNameChoice_Jerry::
    .string "JERRY$"

gNameChoice_John::
    .string "JOHN$"

gNameChoice_Mick::
    .string "MICK$"

gNameChoice_Nick::
    .string "NICK$"

gNameChoice_Rick::
    .string "RICK$"

gNameChoice_Roger::
    .string "ROGER$"

gNameChoice_Storm::
    .string "STORM$"

gNameChoice_Vince::
    .string "VINCE$"

gNameChoice_Will::
    .string "WILL$"

gNameChoice_Anni::
    .string "ANNI$"

gNameChoice_Delia::
    .string "DELIA$"

gNameChoice_Emma::
    .string "EMMA$"

gNameChoice_Faith::
    .string "FAITH$"

gNameChoice_Felicia::
    .string "FELICIA$"

gNameChoice_Holly::
    .string "HOLLY$"

gNameChoice_Jenny::
    .string "JENNY$"

gNameChoice_Kate::
    .string "KATE$"

gNameChoice_Lana::
    .string "LANA$"

gNameChoice_Marge::
    .string "MARGE$"

gNameChoice_Morgan::
    .string "MORGAN$"

gNameChoice_Nora::
    .string "NORA$"

gNameChoice_Pat::
    .string "PAT$"

gNameChoice_Rei::
    .string "REI$"

gNameChoice_Ruth::
    .string "RUTH$"

gNameChoice_Sara::
    .string "SARA$"

gNameChoice_Selma::
    .string "SELMA$"

gNameChoice_Suvi::
    .string "SUVI$"

gNameChoice_Tara::
    .string "TARA$"

gControlsGuide_Text_Intro::
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gControlsGuide_Text_DPad::
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gControlsGuide_Text_AButton::
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
    .string "Press this button to open the\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gControlsGuide_Text_LRButtons::
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gGiovanniSpeech_Text_AskPlayerGender::
    .string "Now tell me.\n"
    .string "Are you a man or a woman?$"

gPikachuIntro_Text_Page1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gPikachuIntro_Text_Page2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gPikachuIntro_Text_Page3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gGiovanniSpeech_Text_WelcomeToTheTeam::
    .string "Right decision…\n"
    .string "We are proud of your participation.\p"
    .string "Welcome to the TEAM ROCKET!\p"
    .string "My name is GIOVANNI.\p"
    .string "I am the master of great\n"
    .string "TEAM ROCKET!\p$"

gGiovanniSpeech_Text_OurTeams::
    .string "Our team's…$"

gGiovanniSpeech_Text_CapturingAllOfThese::
    .string "…goal is capturing all of these\n"
    .string "POKéMON in the world.\p$"

gGiovanniSpeech_Text_WeCapturePokemon::
    .string "Some consider POKéMON as pets,\n"
    .string "some prefer battles or contests,\p"
    .string "some keep them for as some\n"
    .string "measure of self-defense.\p"
    .string "Yet, we capture them to gain\n"
    .string "power and fame.\p$"

gGiovanniSpeech_Text_IWouldLikeToKnowAboutYou::
    .string "But first, I would like to know\n"
    .string "about you.\p$"

gGiovanniSpeech_Text_WhatWasYourName::
    .string "Oh, and...\p"
    .string "What was your name, then?\p$"

gGiovanniSpeech_Text_SoYouArePlayer::
    .string "I understand…\n"
    .string "You're {PLAYER}.$"

gGiovanniSpeech_Text_ThisIsAnotherRecruit::
    .string "This is another recruit of ours.\p"
    .string "He is a great POKéMON TRAINER.\p"
    .string "…From now on, he will work for us\n"
    .string "as well.$"

gGiovanniSpeech_Text_WhatIsYourColleagueName::
    .string "What is your colleague's name?$"

gGiovanniSpeech_Text_ConfirmRivalName::
    .string "…Was it {RIVAL}?$"

gGiovanniSpeech_Text_HisNameIsRival::
    .string "That's correct.\n"
    .string "His name is {RIVAL}.\p$"

gGiovanniSpeech_Text_MakeTeamRocketProud::
    .string "{PLAYER}!\p"
    .string "Now, go and make the TEAM ROCKET\n"
    .string "proud.\p"
    .string "A new world to order awaits us.\n"
    .string "Soon, the world will be ours!$"
