gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Black::
    .string "BLACK$"

gNameChoice_Kirk::
    .string "KIRK$"

gNameChoice_Syd::
    .string "SYD$"

gNameChoice_Adam::
    .string "ADAM$"

gNameChoice_Axl::
    .string "AXL$"

gNameChoice_Cash::
    .string "CASH$"

gNameChoice_Chad::
    .string "CHAD$"

gNameChoice_Damon::
    .string "DAMON$"

gNameChoice_David::
    .string "DAVID$"

gNameChoice_Doug::
    .string "DOUG$"

gNameChoice_Eric::
    .string "ERIC$"

gNameChoice_Frank::
    .string "FRANK$"

gNameChoice_Harry::
    .string "HARRY$"

gNameChoice_Ike::
    .string "IKE$"

gNameChoice_Jerry::
    .string "JERRY$"

gNameChoice_John::
    .string "JOHN$"

gNameChoice_Mick::
    .string "MICK$"

gNameChoice_Nick::
    .string "NICK$"

gNameChoice_Rick::
    .string "RICK$"

gNameChoice_Roger::
    .string "ROGER$"

gNameChoice_Storm::
    .string "STORM$"

gNameChoice_Vince::
    .string "VINCE$"

gNameChoice_Will::
    .string "WILL$"

gNameChoice_Anni::
    .string "ANNI$"

gNameChoice_Delia::
    .string "DELIA$"

gNameChoice_Emma::
    .string "EMMA$"

gNameChoice_Faith::
    .string "FAITH$"

gNameChoice_Felicia::
    .string "FELICIA$"

gNameChoice_Holly::
    .string "HOLLY$"

gNameChoice_Jenny::
    .string "JENNY$"

gNameChoice_Kate::
    .string "KATE$"

gNameChoice_Lana::
    .string "LANA$"

gNameChoice_Marge::
    .string "MARGE$"

gNameChoice_Morgan::
    .string "MORGAN$"

gNameChoice_Nora::
    .string "NORA$"

gNameChoice_Pat::
    .string "PAT$"

gNameChoice_Rei::
    .string "REI$"

gNameChoice_Ruth::
    .string "RUTH$"

gNameChoice_Sara::
    .string "SARA$"

gNameChoice_Selma::
    .string "SELMA$"

gNameChoice_Suvi::
    .string "SUVI$"

gNameChoice_Tara::
    .string "TARA$"

gGiovanniSpeech_Text_AskPlayerGender::
    .string "Now tell me.\n"
    .string "Are you a man or a woman?$"

gKoffingIntro_Text_Page1::
    .string "A most unusual story is about to\n"
    .string "unfold, a different point of view\n"
    .string "in the world of POKéMON: A villain.\n"
    .string "\n"
    .string "You'll begin as a TEAM ROCKET GRUNT\n"
    .string "and gradually you'll climb the\n"
    .string "ladder to the top as you unravel\n"
    .string "the mythical mysteries.$"

gKoffingIntro_Text_Page2::
    .string "Five years ago, TEAM ROCKET was\n"
    .string "regrettably defeated by a prodigious\n"
    .string "child. However, those days are already\n"
    .string "behind them.\n"
    .string "\n"
    .string "After learning their lesson, the team\n"
    .string "once more returns, more vengeful and\n"
    .string "tenacious than they have ever been.$"

gKoffingIntro_Text_Page3::
    .string "This is a perilous mission driven by\n"
    .string "twisted morals, where you build a\n"
    .string "mighty crime syndicate.\n"
    .string "\n"
    .string "\n"
    .string "Press the A Button to embark on\n"
    .string "your grand heist!$"

gGiovanniSpeech_Text_WelcomeToTheTeam::
    .string "Right decision…\n"
    .string "We are proud of your participation.\p"
    .string "Welcome to the TEAM ROCKET!\p"
    .string "My name is GIOVANNI.\p"
    .string "I am the master of great\n"
    .string "TEAM ROCKET!\p$"

gGiovanniSpeech_Text_OurTeams::
    .string "Our team's…$"

gGiovanniSpeech_Text_CapturingAllOfThese::
    .string "…goal is capturing all of these\n"
    .string "POKéMON in the world.\p$"

gGiovanniSpeech_Text_WeCapturePokemon::
    .string "Some consider POKéMON as pets,\n"
    .string "some prefer battles or contests,\p"
    .string "some keep them for as some\n"
    .string "measure of self-defense.\p"
    .string "Yet, we capture them to gain\n"
    .string "power and fame.\p$"

gGiovanniSpeech_Text_IWouldLikeToKnowAboutYou::
    .string "But first, I would like to know\n"
    .string "about you.\p$"

gGiovanniSpeech_Text_WhatWasYourName::
    .string "Oh, and...\p"
    .string "What was your name, then?\p$"

gGiovanniSpeech_Text_SoYouArePlayer::
    .string "I understand…\n"
    .string "You're {PLAYER}.$"

gGiovanniSpeech_Text_ThisIsAnotherRecruit::
    .string "This is another recruit of ours.\p"
    .string "He is a great POKéMON TRAINER.\p"
    .string "…From now on, he will work for us\n"
    .string "as well.$"

gGiovanniSpeech_Text_WhatIsYourColleagueName::
    .string "What is your colleague's name?$"

gGiovanniSpeech_Text_ConfirmRivalName::
    .string "…Was it {RIVAL}?$"

gGiovanniSpeech_Text_HisNameIsRival::
    .string "That's correct.\n"
    .string "His name is {RIVAL}.\p$"

gGiovanniSpeech_Text_MakeTeamRocketProud::
    .string "{PLAYER}!\p"
    .string "Now, go and make the TEAM ROCKET\n"
    .string "proud.\p"
    .string "A new world to order awaits us.\n"
    .string "Soon, the world will be ours!$"
