Text_FirstShouldRestoreMonsHealth::
	.string "First, you should restore your\n"
	.string "POKéMON to full health.$"

Text_MonsHealedShouldBuyPotions::
	.string "Your POKéMON have been healed\n"
	.string "to perfect health.\p"
	.string "If your POKéMON's energy, HP,\n"
	.string "is down, please come see us.\p"
	.string "If you're planning to go far in the\n"
	.string "field, you should buy some POTIONS\l"
	.string "at the POKéMON MART.\p"
	.string "We hope you excel!$"

Text_MonsHealed::
	.string "Your POKéMON have been healed\n"
	.string "to perfect health.\p"
	.string "We hope you excel!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "NURSE: {PLAYER}!\n"
	.string "Welcome back.\p"
	.string "We somehow managed to\n"
	.string "return here safely.\p"
	.string "You gotta take some rest.$"

Text_MomExplainHPGetPotions::
	.string "NURSE: Cool. Now you and your\n"
	.string "POKéMON are looking much better.\p"
	.string "You gotta be careful out there\n"
	.string "with all the cops and all other\l"
	.string "kind of dangerous gangs.\p"
	.string "If your POKéMON lose their HP,\n"
	.string "you can restore them at any\l"
	.string "of our hideouts.\p"
	.string "I think you should buy POTIONS,\n"
	.string "in our bribed POKéMON MARTS or\l"
	.string "some of the hideouts.\p"
	.string "Anyway. Later.$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} panicked and lost ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"

Text_WhitedOut::
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} whited out!$"
