Text_FirstShouldRestoreMonsHealth::
	.string "{COLOR LIGHT_RED}NURSE: {COLOR RED}First, you should\n"
	.string "restore your POKéMON to full\l"
	.string "health.$"

Text_MonsHealed::
	.string "{COLOR LIGHT_RED}NURSE: {COLOR RED}Your POKéMON have been\n"
	.string "healed to perfect health.\p"
	.string "Be careful out there.$"

Text_HadQuiteAnExperienceTakeRest::
	.string "{COLOR LIGHT_RED}NURSE: {COLOR RED}{PLAYER}!\n"
	.string "Welcome back.\p"
	.string "We somehow managed to\n"
	.string "return here safely.\p"
	.string "You gotta take some rest.$"

Text_MomExplainHPGetPotions::
	.string "{COLOR LIGHT_RED}NURSE: {COLOR RED}Cool. Now you and your\n"
	.string "POKéMON are looking much better.\p"
	.string "You gotta be careful out there\n"
	.string "with all the cops and all other\l"
	.string "kind of dangerous gangs.\p"
	.string "If your POKéMON lose their HP,\n"
	.string "you can restore them at any\l"
	.string "of our hideouts.\p"
	.string "I think you should buy POTIONS,\n"
	.string "in our bribed POKéMON MARTS or\l"
	.string "some of the hideouts.\p"
	.string "Anyway. Later.$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} panicked and lost ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"

Text_WhitedOut::
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} whited out!$"
