PewterCity_PewterBase_MapScripts::
	.byte 0

PewterCity_PewterBase_Rocket_1::
	msgbox PewterCity_PewterBase_Text_OurEngineersDeveloped, MSGBOX_NPC
	end

PewterCity_PewterBase_Rocket_2::
	msgbox PewterCity_PewterBase_Text_ThoseStairsLeadYou, MSGBOX_NPC
	end

PewterCity_PewterBase_Rocket_3::
	msgbox PewterCity_PewterBase_Text_SoonTeamRocket, MSGBOX_NPC
	end

PewterCity_PewterBase_Black::
	msgbox PewterCity_PewterBase_Text_BrockBuriedTheTreasure, MSGBOX_NPC
	end
