PewterCity_PewterBase_Text_OurEngineersDeveloped::
    .string "Our engineers developed the TRADE\n"
    .string "technology for TEAM ROCKET.\p"
    .string "Go through the door, you'll see.$"

PewterCity_PewterBase_Text_ThoseStairsLeadYou::
    .string "Those stairs lead you to the\n"
    .string "TEAM ROCKET HEALING CENTER.$"

PewterCity_PewterBase_Text_SoonTeamRocket::
    .string "Soon, TEAM ROCKET will order this\n"
    .string "region, no, even the world!$"

PewterCity_PewterBase_Text_BrockBuriedTheTreasure::
    .string "{COLOR LIGHT_RED}{RIVAL}:{COLOR BLUE} BROCK buried the\n"
    .string "treasure named ROTSMELL into the\l"
    .string "basement of his GYM. He is very\l"
    .string "tough, so be careful.$"
