PewterCity_PewterBase_HealingCenter_Text_MyPokemonHasFainted::
    .string "My POKéMON has fainted while I\n"
    .string "was travelling because of poison.\l"
    .string "So I came here for healing.$"

PewterCity_PewterBase_HealingCenter_Text_PokemonWithStatusProblems::
    .string "POKéMON with status problems can\n"
    .string "be caught easier than the healthy\l"
    .string "ones. It is also easier to steal\l"
    .string "them.$"

PewterCity_PewterBase_HealingCenter_Text_HaveYouHeardAboutTheProfilingSystem::
    .string "Hi, glad to meet you!\p"
    .string "Have you heard about the\n"
    .string "profiling system that the police\l"
    .string "uses? We try to develop something\l"
    .string "similar as well to avoid the\l"
    .string "impostors from the government.$"
