ViridianCity_ViridianBase_TrainingClass_Text_BlackboardListsStatusProblems::
    .string "The blackboard lists POKéMON\n"
    .string "STATUS problems during battles.$"

ViridianCity_ViridianBase_TrainingClass_Text_ReadWhichTopic::
    .string "Which topic do you want to read?$"

ViridianCity_ViridianBase_TrainingClass_Text_ExplainSleep::
    .string "A POKéMON can't attack if it's\n"
    .string "asleep.\p"
    .string "POKéMON will stay asleep even\n"
    .string "after battles.\p"
    .string "Use AWAKENING to awaken one\n"
    .string "from sleep.$"

ViridianCity_ViridianBase_TrainingClass_Text_ExplainBurn::
    .string "A burn reduces ATTACK power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use BURN HEAL to cure a burn.$"

ViridianCity_ViridianBase_TrainingClass_Text_ExplainPoison::
    .string "When poisoned, a POKéMON's health\n"
    .string "steadily drops.\p"
    .string "Poison lingers after battles.\n"
    .string "Use an ANTIDOTE to cure poison!$"

ViridianCity_ViridianBase_TrainingClass_Text_ExplainFreeze::
    .string "A frozen POKéMON becomes\n"
    .string "helplessly immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use ICE HEAL to thaw out the\n"
    .string "suffering POKéMON.$"

ViridianCity_ViridianBase_TrainingClass_Text_ExplainParalysis::
    .string "Paralysis reduces SPEED and may\n"
    .string "prevent the POKéMON from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use PARLYZ HEAL for treatment.$"

ViridianCity_ViridianBase_TrainingClass_Text_ReadTheText::
    .string "Read the text on the board.\n"
    .string "There is useful info on it!$"

ViridianCity_ViridianBase_TrainingClass_Text_OneOfTheEldest::
    .string "I am the one of the eldest\n"
    .string "members in TEAM ROCKET. This is a\l"
    .string "small school, although they name\l"
    .string "it the ACADEMY.$"
