RecruitBase_Entrance_Text_RecruitHelp::
    .string "RECRUIT HELP\n"
    .string "Pressing L and R buttons will help\l"
    .string "you.$"

RecruitBase_Entrance_Text_Medic::
    .string "I am a medic of TEAM ROCKET. I\n"
    .string "heal POKéMONs when they hurt.$"

RecruitBase_Entrance_BoxesContainSuits::
    .string "These boxes are filled with\n"
    .string "TEAM ROCKET suits. We bring them\l"
    .string "for recruits.$"

RecruitBase_Entrance_WeGotPokedex::
    .string "We “borrowed” the POKéDEX from a\n"
    .string "maniac named BILL near CERULEAN\l"
    .string "CITY.$"

RecruitBase_Entrance_ThereIsLabNearby::
    .string "I heard there is a POKéMON LAB\n"
    .string "near our recruit base.$"

RecruitBase_Entrance_Text_IToldEverything::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}I told everything\n"
    .string "to the technician, and he wants to\l"
    .string "speak with us now!$"

RecruitBase_Entrance_Text_HeardYouGotPokemon::
    .string "{COLOR LIGHT_RED}TECHNICIAN: {COLOR BLUE}I heard you got\n"
    .string "a POKéMON. That's great!\l"
    .string "{PLAYER} and {RIVAL}! During your\l"
    .string "journey you will need something\l"
    .string "important.$"

RecruitBase_Entrance_Text_WhatAreThey::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}What're these\n"
    .string "encyclopedia-looking\l"
    .string "devices?$"

RecruitBase_Entrance_Text_TheyArePokedex::
    .string "They are POKéDEX! It saves a\n"
    .string "recording when you encounter\l"
    .string "POKéMONs! I think\l"
    .string "it will help you two.$"

RecruitBase_Entrance_Text_PlayerGetsPokedex::
    .string "{PLAYER} got a POKéDEX!$"

RecruitBase_Entrance_Text_TheOtherOne::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}Other one\n"
    .string "is mine!$"

RecruitBase_Entrance_Text_ThankYou::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}Thanks for\n"
    .string "everything! Farewell!$"

RecruitBase_Entrance_Text_IHopeYouComplete::
    .string "{COLOR LIGHT_RED}TECHNICIAN: {COLOR BLUE}{PLAYER}!\n"
    .string "I hope you complete this mission!\l"
    .string "Go and make the boss proud!$"
