ViridianForest_Text_IpaAgentsAreEverywhere::
    .string "{COLOR BLUE}IPA agents are everywhere. Be\n"
    .string "careful, they have extremely,\l"
    .string "really extremely powerful POKéMON\l"
    .string "with them. When you encounter\l"
    .string "them, you have no chance!\p"
    .string "They are identifiable with their\n"
    .string "green hats.\p"
    .string "I must go for now. Good luck in\n"
    .string "your hunt!$"

ViridianForest_Text_MyAntidoteGotStuck::
    .string "My ANTIDOTE got stuck on\n"
    .string "a tree.$"

ViridianForest_Text_HeyYouCannotPass::
    .string "Hey! You cannot pass!$"

ViridianForest_Text_OnASecondThought::
    .string "On a second thought, BUG POKéMON"
    .string "might be not a good choice.$"

ViridianForest_Text_OopsYouWontSteal::
    .string "Oops! You won't steal my POKéMON,\n"
    .string "will you?$"

ViridianForest_Text_INeverLikedTeamRocket::
    .string "I never liked TEAM ROCKET.$"

ViridianForest_Text_AlreadyGotDefeated::
    .string "Already got defeated before"
    .string "realizing.$"

ViridianForest_Text_AllMyPokemonAreDefeated::
    .string "All my POKéMON are defeated. Go!$"

ViridianForest_Text_IMightBeLittle::
    .string "I might be little, but I cannot\n"
    .string "allow you to pass through.$"

ViridianForest_Text_BlastOff::
    .string "Blast off!$"

ViridianForest_Text_YouWonNowGo::
    .string "You won, now go…$"

ViridianForest_Text_HeyWaitUp::
    .string "Hey, wait up!\n"
    .string "Couldn't IPA find you?$"

ViridianForest_Text_IUnderstand::
    .string "I understand.$"

ViridianForest_Text_DamnYouJerk::
    .string "Damn you jerk.$"

ViridianForest_Text_MyPokemonCanEvolve::
    .string "My POKéMON can evolve quickly!$"

ViridianForest_Text_ILost::
    .string "I lost!$"

ViridianForest_Text_IHopeIpaFindsYou::
    .string "I hope IPA finds you.$"

ViridianForest_Text_IAmNotWithMyPokemon::
    .string "I am not with my POKéMON. Or I\n"
    .string "would crush you.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "TRAINER TIPS\p"
    .string "If your POKéMON are weak and you\n"
    .string "want to avoid battles, stay away\l"
    .string "from grassy areas!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "TRAINER TIPS\p"
    .string "For poison, use ANTIDOTE!\n"
    .string "Get it at POKéMON MARTS!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "TRAINER TIPS\p"
    .string "It is illegal to catch a POKéMON\n"
    .string "that belongs to someone else.\p"
    .string "Throw POKé BALLS only at wild\n"
    .string "POKéMON to catch them!$"

ViridianCity_Text_LikeICare::
    .string "Heh…\n"
    .string "Like I care about law and order.$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "TRAINER TIPS\p"
    .string "Weaken POKéMON before attempting\n"
    .string "capture!\p"
    .string "When healthy, they may escape!$"

ViridianForest_Text_LeavingViridianForest::
    .string "LEAVING VIRIDIAN FOREST\n"
    .string "PEWTER CITY AHEAD$"

ViridianForest_Text_FinallyICaughtYou::
    .string "Finally, I caught you!$"

ViridianForest_Text_HowTheHell::
    .string "How the hell can you win against\n"
    .string "us?$"

ViridianForest_Text_ShockingNews::
    .string "Shocking news. We need"
    .string "reinforcements against this"
    .string "criminal!$"
