
RecruitBase_MainHall_Text_NeedsPassword::
    .string "The login screen is open and needs\n"
    .string "a password to access.$"

RecruitBase_MainHall_Text_RecruitBaseSign::
    .string "THE RECRUIT BASE$"

RecruitBase_MainHall_Text_Box_Empty::
    .string "An empty box…$"

RecruitBase_MainHall_Text_Box_TeamRocketSuits::
    .string "A label is stuck on this box:\n"
    .string "“TEAM ROCKET SUITS”$"

RecruitBase_MainHall_Text_Box_Pokeballs::
    .string "Some POKéBALLs are stored in this box.$"

RecruitBase_MainHall_Text_AccordingToLegend::
    .string "According to the legend,\n"
    .string "if all of eight sacred treasures\l"
    .string "combine, legendary POKéMON\l"
    .string "will appear.$"

RecruitBase_MainHall_Text_WeAreTheNewMembers::
    .string "We are the new members of TEAM\n"
    .string "ROCKET.$"

RecruitBase_MainHall_Text_CollectingTreasures::
    .string "The treasures… Collecting them\n"
    .string "will be hard.$"

RecruitBase_MainHall_Text_TeamMagma::
    .string "TEAM MAGMA is after the treasures…$"

RecruitBase_MainHall_Text_WillOrderTheWorld::
    .string "Soon, TEAM ROCKET will order the\n"
    .string "world.$"

RecruitBase_MainHall_Text_ExceedsYourAuthority::
    .string "The underground base exceeds\n"
    .string "your authority.$"

RecruitBase_MainHall_Text_ComeHere::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}{RIVAL}! Come here!"

RecruitBase_MainHall_Text_BossWantsToSpeak::
    .string "{COLOR LIGHT_RED}{RIVAL}:{COLOR BLUE} The boss wants\n"
    .string "to speak with you.\l"
    .string "{COLOR LIGHT_RED}GIOVANNI: {COLOR BLUE}You made the\l"
    .string "TEAM ROCKET proud, {PLAYER}! We\l"
    .string "finally got one of the artifacts,\l"
    .string "and gym leader BROCK is imprisoned\l"
    .string "to the basement.\l"
    .string "Also, we have some bad news for you…\l"
    .string "The TEAM MAGMA is coming from\l"
    .string "HOENN to search for the artifacts too.\l"
    .string "I don't know what they are\l"
    .string "planning, but that's not good.\l"
    .string "To escape quickly, you need\l"
    .string "something. Yes, they're RUNNING\l"
    .string "SHOES!$"

RecruitBase_MainHall_Text_PlayerGetsRunningShoes::
    .string "{PLAYER} received the\n"
    .string "RUNNING SHOES from GIOVANNI.$"

RecruitBase_MainHall_Text_PlayerSwitchesRunningShoes::
    .string "{PLAYER} switched shoes with the\n"
    .string "RUNNING SHOES.$"

RecruitBase_MainHall_Text_GiovanniDismissesPlayer::
    .string "{COLOR LIGHT_RED}GIOVANNI: {COLOR BLUE}Like this… You\n"
    .string "are free now. Good luck, {PLAYER}\l"
    .string "and {RIVAL}!$"

RecruitBase_MainHall_Text_BlackGoesAhead::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}Then, I am going,\n"
    .string "too. Let's go.$"
