ViridianCity_ViridianBase_Text_BeyondTheDoor::
    .string "Beyond the door, there is an\n"
    .string "academy.$"

ViridianCity_ViridianBase_Text_GuysLikeYou::
    .string "Guys like you can't understand\n"
    .string "that how the machines work. You\l"
    .string "are not a technician.$"

ViridianCity_ViridianBase_Text_HospitalSign::
    .string "TEAM ROCKET\n"
    .string "POKéMON HEALING CENTER$"
