RecruitBase_RegistrationRoom_Text_NoSmoking::
    .string "Please do not smoke indoors.$"

RecruitBase_RegistrationRoom_Text_GoToFront::
    .string "Go to the front of the desk. I\n"
    .string "can't finish your registration\l"
    .string "like this!$"

RecruitBase_RegistrationRoom_Text_RecruitWelcome::
    .string "Welcome to the TEAM ROCKET,\n"
    .string "recruit!$"

RecruitBase_RegistrationRoom_Text_MemberWelcome::
    .string "Hi, {PLAYER}! Good to see you again!$"

RecruitBase_RegistrationRoom_Text_RegistrationFinalRemarks::
    .string "Hmm... Name: {PLAYER}, your age is 23…\n"
    .string "You were a former POKéMART\l"
    .string "employee… You've quit there\l"
    .string "to join the TEAM ROCKET. Okay…\l"
    .string "Your registration is complete!$"

RecruitBase_RegistrationRoom_Text_GiovanniIntroduction::
    .string "{COLOR LIGHT_RED}GIOVANNI: {COLOR BLUE}So you are the new\n"
    .string "member. Do you know what our\l"
    .string "current goal is? Listen, recruit.\l"
    .string "The archeologists of KANTO discovered\l"
    .string "eight unique artifacts here in\l"
    .string "this region.\p"
    .string "Our goal is getting them to make\n"
    .string "the TEAM ROCKET the most powerful\l"
    .string "organization in the world. The\l"
    .string "artifacts were told in legends.\l"
    .string "Every piece was belonged a\l"
    .string "legendary POKéMON, they say. Now\l"
    .string "the archeologists' research tells\l"
    .string "us that these artifacts contain a\l"
    .string "high energy potential. Your\l"
    .string "objective is to steal all of them.\l"
    .string "Good luck, recruit {PLAYER}!$"

RecruitBase_RegistrationRoom_Text_ShouldCompleteRegistrationFirst::
    .string "I should complete my registration\n"
    .string "to TEAM ROCKET first.$"
