PewterCity_Text_RecruitHelpEarningExp::
    .string "RECRUIT HELP\p"
    .string "All POKéMON that fought in battle,\n"
    .string "even briefly, get EXP Points.$"

PewterCity_Text_RumorsSay::
    .string "Rumors say artifacts of KANTO\n"
    .string "are related to legendaries.\l"
    .string "People like you attempt to steal\l"
    .string "it!$"

PewterCity_Text_OhNoItsStolen::
    .string "Oh no, it is stolen! BROCK failed\n"
    .string "to protect the treasure!$"

PewterCity_Text_MuseumOfScienceSign::
    .string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_GymSign::
    .string "PEWTER CITY POKéMON GYM\n"
    .string "LEADER: BROCK\l"
    .string "The Rock-Solid POKéMON TRAINER!$"

PewterCity_Text_CitySign::
    .string "PEWTER CITY\n"
    .string "A Stone Gray City$"

PewterCity_Text_WeHaveSecretBases::
    .string "We have secret bases built in\n"
    .string "the woods of almost every city.$"

PewterCity_Text_ThereAreBothersome::
    .string "There are bothersome wild POKéMON\n"
    .string "in the grass. I use REPEL to avoid\l"
    .string "them.$"

PewterCity_Text_ICantLetTheIPAAgents::
    .string "I can't let the IPA agents notice\n"
    .string "me.$"

PewterCity_Text_IPAAgentsAreFocused::
    .string "The IPA agents are focused on the\n"
    .string "incident now. I can't let them\l"
    .string "notice me.$"

PewterCity_Text_StandOffMyGarden::
    .string "Hey! Stand off my garden.$"

PewterCity_Text_NoMatterWhoComes::
    .string "No matter who comes, we accept\n"
    .string "everybody to MUSEUM. Even you.$"

PewterCity_Text_AfterTheRobbery::
    .string "{COLOR LIGHT_RED}{RIVAL}:{COLOR BLUE} Hey, {PLAYER}!\p"
    .string "After the robbery,\n"
    .string "I got POKé BALLS and caught a\l"
    .string "PIDGEY. Guess what happened then?\l"
    .string "I fought the artifact holder. Eh,\l"
    .string "I lost. I am going to the base.\l"
    .string "See you later.$"

PewterCity_Text_PewterCityGymLeader::
    .string "PEWTER CITY GYM leader BROCK hides\n"
    .string "an artifact named ROTSMELL here,\l"
    .string "to protect it from TEAM ROCKET.\l"
    .string "I am sure that he is tough, and\l"
    .string "you won't get the artifact.$"

PewterCity_Text_BrockLeft::
    .string "BROCK left with a TEAM ROCKET\n"
    .string "guy!\p"
    .string "What's happening on there?$"

PewterCity_Text_SomebodyStole::
    .string "Somebody stole the ROTSMELL\n"
    .string "artifact! Nobody knows where\l"
    .string "BROCK is!$"

PewterCity_Text_PewterGymDoorsAreLocked::
    .string "PEWTER GYM's doors are locked…$"
