PewterCity_Text_RecruitHelpEarningExp::
    .string "RECRUIT HELP\p"
    .string "All POKéMON that fought in battle,\n"
    .string "even briefly, get EXP Points.$"

PewterCity_Text_MuseumOfScienceSign::
    .string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_GymSign::
    .string "PEWTER CITY POKéMON GYM\n"
    .string "LEADER: BROCK\l"
    .string "The Rock-Solid POKéMON TRAINER!$"

PewterCity_Text_CitySign::
    .string "PEWTER CITY\n"
    .string "A Stone Gray City$"

PewterCity_Text_WeHaveSecretBases::
    .string "We have secret bases built in\n"
    .string "the woods of almost every city.$"

PewterCity_Text_ThereAreBothersome::
    .string "There are bothersome wild POKéMON\n"
    .string "in the grass. I use REPEL to avoid\l"
    .string "them.$"

PewterCity_Text_AfterTheRobbery::
    .string "{COLOR LIGHT_RED}{RIVAL}:{COLOR BLUE} Hey, {PLAYER}!\p"
    .string "After the robbery,\n"
    .string "I got POKé BALLS and caught a\l"
    .string "PIDGEY. Guess what happened then?\l"
    .string "I fought the artifact holder. Eh,\l"
    .string "I lost. I am going to the base.\l"
    .string "See you later.$"
