PalletTown_ProfessorOaksLab_Text_ComputerShutDown::
    .string "The computer is shut down.$"

PalletTown_ProfessorOaksLab_Text_SomebodyHelpMe::
    .string "{COLOR LIGHT_RED}OAK:{COLOR BLUE} Somebody help me!\n"
    .string "He has a gun!$"

PalletTown_ProfessorOaksLab_Text_GoAway::
    .string "{COLOR LIGHT_RED}ASSISTANT: {COLOR BLUE} TEAM ROCKET!\n"
    .string "Why did you came here? Go away!$"

PalletTown_ProfessorOaksLab_Text_ShutYourMouth::
    .string "{COLOR LIGHT_RED}{RIVAL}:{COLOR BLUE} Shut your mouth and\n"
    .string "wait here. Don't move,\l"
    .string "or your end won't be so good.$"

PalletTown_ProfessorOaksLab_Text_ComeOnNow::
    .string "{COLOR LIGHT_RED}{RIVAL}:{COLOR BLUE} Come on now!$"

PalletTown_ProfessorOaksLab_Text_GiveMeYourPokemon::
    .string "{COLOR LIGHT_RED}{RIVAL}:{COLOR BLUE} Give me your POKéMON! Quick!\n"
    .string "I have a gun!\p"
    .string "{COLOR LIGHT_RED}OAK:{COLOR BLUE} Stay away! I won't\n"
    .string "give any of my POKéMON!$"

PalletTown_ProfessorOaksLab_Text_ChooseFromTable::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}{PLAYER}! Choose a\n"
    .string "POKéMON from the\l"
    .string "table, then we go!$"

PalletTown_ProfessorOaksLab_Text_SmallTask::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}Oh, it's a small\n"
    .string "task. Give me your POKéMON!$"

PalletTown_ProfessorOaksLab_Text_Scream::
    .string "EEEEEEEKK!$"

PalletTown_ProfessorOaksLab_Text_WhereAreYouGoing::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}{PLAYER}! Where are you going?\n"
    .string "We have unfinished business here.$"
