PalletTown_ProfessorOaksLab_Text_ElmsEmail::
    .string "There is an e-mail on the screen\n"
    .string "that can be read:\p"
    .string "“Dear SAMUEL,\n"
    .string "I wanted to thank you for the other\l"
    .string "day when you visited NEW BARK to\l"
    .string "see the most recent results of my\l"
    .string "UNOWN research. Since you needed\l"
    .string "some POKéMON for new kids who just\l"
    .string "began their journeys I'll give\l"
    .string "you some JOHTO species that would\l"
    .string "do quite well. By the way, say hi\l"
    .string "to GREEN for me.\p"
    .string "Sincerely,\n"
    .string "PROF. ELM.”$"

PalletTown_ProfessorOaksLab_Text_SomebodyHelpMe::
    .string "{COLOR LIGHT_RED}OAK:{COLOR BLUE} Somebody help me!\n"
    .string "He has a gun!$"

PalletTown_ProfessorOaksLab_Text_GoAway::
    .string "{COLOR LIGHT_RED}ASSISTANT:{COLOR BLUE} TEAM ROCKET!\n"
    .string "Why did you came here? Go away!$"

PalletTown_ProfessorOaksLab_Text_ShutYourMouth::
    .string "{COLOR LIGHT_RED}{RIVAL}:{COLOR BLUE} Shut your mouth and\n"
    .string "wait here. Don't move,\l"
    .string "or your end won't be so good.$"

PalletTown_ProfessorOaksLab_Text_ComeOnNow::
    .string "{COLOR LIGHT_RED}{RIVAL}:{COLOR BLUE} Come on now!$"

PalletTown_ProfessorOaksLab_Text_GiveMeYourPokemon::
    .string "{COLOR LIGHT_RED}{RIVAL}:{COLOR BLUE} Give me your POKéMON! Quick!\n"
    .string "I have a gun!\p"
    .string "{COLOR LIGHT_RED}OAK:{COLOR BLUE} Stay away! I won't\n"
    .string "give any of my POKéMON!$"

PalletTown_ProfessorOaksLab_Text_ChooseFromTable::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}{PLAYER}! Choose a\n"
    .string "POKéMON from the\l"
    .string "table, then we go!$"

PalletTown_ProfessorOaksLab_Text_SmallTask::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}Oh, it's a small\n"
    .string "task. Give me your POKéMON!$"

PalletTown_ProfessorOaksLab_Text_Scream::
    .string "EEEEEEEKK!$"

PalletTown_ProfessorOaksLab_Text_WhereAreYouGoing::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}{PLAYER}! Where are you going?\n"
    .string "We have unfinished business here.$"

PalletTown_ProfessorOaksLab_Text_FirstShouldStealPokemon::
    .string "First, I should steal a POKéMON!$"

PalletTown_ProfessorOaksLab_Text_AlreadyGotOne::
    .string "Already got one...$"

PalletTown_ProfessorOaksLab_Text_StealingDecision::
    .string "Hmm... This is a {STR_VAR_1}!\nShould I steal it?$"

PalletTown_ProfessorOaksLab_Text_StolePokemon::
    .string "{PLAYER} stole the {STR_VAR_1}!\nIt is quite good!$"

PalletTown_ProfessorOaksLab_Text_Nickname::
    .string "Do you want to give a nickname to\n"
    .string "this stolen {STR_VAR_1}?$"
