SecretWoods_Text_Scientist::
    .string "With the new technology, people\n"
	.string "can store POKéMON and item in\l"
	.string "their PC. I am a hacker in TEAM\n"
	.string "ROCKET. We are researching to\l"
    .string "crack into those PCs I mentioned.$"

SecretWoods_Text_FemaleRocket::
    .string "It's a great place to hide here.$"

SecretWoods_Text_MaleRocket::
    .string "Without POKéMONs, you cannot\n"
	.string "wander in tall grass.$"
	
SecretWoods_Text_MaleRocketAfterLabInvasion::
    .string "Oh wait, you got your POKéMON!$"

SecretWoods_Text_RecruitBaseSign::
    .string "SECRET RECRUIT BASE$"

SecretWoods_Text_RecruitHelpSign::
    .string "RECRUIT HELP\p"
	.string "To open MENU, press START.$"
    