ViridianCity_School_MapScripts::
	.byte 0

ViridianCity_School_Lass::
	trainerbattle_single TRAINER_VIRIDIAN_SCHOOL_LASS, ViridianCity_School_Text_TeamRocket, ViridianCity_School_Text_OhNo
	msgbox ViridianCity_School_Text_IAmSoScared, MSGBOX_NPC
	end

ViridianCity_School_Woman::
	msgbox ViridianCity_School_Text_PleaseJustGo, MSGBOX_NPC
	end

ViridianCity_School_Notebook::
	msgbox ViridianCity_School_Text_Notebook, MSGBOX_SIGN
	end

ViridianCity_School_Blackboard::
	msgbox ViridianCity_School_Text_Blackboard, MSGBOX_SIGN
	end

ViridianCity_School_Bookshelf::
	msgbox ViridianCity_School_Text_SpecialFeatureAreaZero, MSGBOX_SIGN
	end
