ViridianCity_School_Text_PleaseJustGo::
    .string "Please… Just go! I beg you won't\n"
    .string "hurt us.$"

ViridianCity_School_Text_Blackboard::
    .string "The blackboard is full of\n"
    .string "nonsensical text.$"

ViridianCity_School_Text_Notebook::
    .string "Many things are drawn on the notebook\n"
    .string "out of the student's boredom.\p"
    .string "But a circular shape with two\n"
    .string "legs and a backpack which has\l"
    .string "visor-like eyes is especially\l"
    .string "intriguing. Is that a POKéMON?$"

ViridianCity_School_Text_TurnThePage::
    .string "Turn the page?$"

ViridianCity_School_Text_TeamRocket::
    .string "TEAM ROCKET!$"

ViridianCity_School_Text_OhNo::
    .string "Oh no!$"

ViridianCity_School_Text_IAmSoScared::
    .string "I am so… scared… Leave me alone…$"

ViridianCity_School_Text_SpecialFeatureAreaZero::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: AREA ZERO,\n"
	.string "the mysterious region of PALDEA!\p"
	.string "PROF. BRIAR's research about\n"
	.string "something called Paradox POKéMON\l"
    .string "makes us question everything we\l"
    .string "know about POKéMON world, and\l"
    .string "even the concept of time and\l"
    .string "space.$"
