Route22_JohtoEntrance_Text_PassingBeyondThisPoint::
    .string "Passing beyond this point is\n"
    .string "restricted for you!$"

Route22_JohtoEntrance_Text_HoldOnThere::
    .string "Hold on there! You cannot\n"
    .string "pass with ease.\l"
    .string "Please show your ticket to pass.\p"
    .string "You don't have any? I doubt that\n"
    .string "they would give tickets to TEAM\l"
    .string "ROCKET members.$"
