Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "Do not worry about being a TEAM\n"
    .string "ROCKET grunt! Some of our branches\l"
    .string "have some kind of, ehm, agreement\l"
    .string "with your colleagues.\p"
    .string "Anyway. So, our market chain is\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in VIRIDIAN CITY.\p"
    .string "I would like to give you a sample.\n"
    .string "Here you go!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Come visit us! We are selling POKé\n"
    .string "BALLS for catching POKéMON too.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

Route1_Text_SomebodySuitedLikeYou::
    .string "Somebody suited like you stole\n"
    .string "a POKéMON from OAK's lab!$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"

