SecretPath_North_Text_NoNeedToStealEachTime::
    .string "You don't need to steal\n"
    .string "POKéMON each time. With POKé BALLS\l"
    .string "you can catch wild POKéMON! Here,\l"
    .string "take it.$"

SecretPath_North_Text_PokeballIsConvenient::
    .string "POKé BALL is a convenient\n"
    .string "technology, really!$"

SecretPath_North_PutPokeballAway::
    .string "{PLAYER} put the POKé BALL away in\n"
    .string "the BAG's POKé BALLS POCKET.$"
