ViridianCity_Text_ThesePokeballsInYourWaist::
    .string "There are POKé BALLS in your\n"
    .string "waist. I hope you didn't steal\l"
    .string "them.$"

ViridianCity_Text_DoNotBotherUs::
    .string "Oh, do not bother us please.\n"
    .string "Especially you mysterious looking\l"
    .string "ones.$"

ViridianCity_Text_ThisPeakLooksSoStrange::
    .string "This peak looks so strange…$"

ViridianCity_Text_PassingThroughViridianForest::
    .string "Passing through the VIRIDIAN\n"
    .string "FOREST is not that hard, really!$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY\n"
    .string "The Eternally Green Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "RECRUIT HELP\p"
    .string "Catching POKéMON and leveling them\n"
    .string "make battles easier.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "RECRUIT HELP\p"
    .string "POKéMON have limited PP for every\n"
    .string "ability they use.$"

ViridianCity_Text_ThisPathLeads::
    .string "This path leads to one of our\n"
    .string "secret bases. There is a TEAM\l"
    .string "ROCKET POKéMON HEALING CENTER\l"
    .string "here as well.$"

ViridianCity_Text_ThisBaseHas::
    .string "This base has an academy for TEAM\n"
    .string "ROCKET recruits, and a POKéMON\l"
    .string "HEALING CENTER to heal your\l"
    .string "POKéMON.$"

ViridianCity_Text_YouFromTeamRocket::
    .string "You from TEAM ROCKET?$"

ViridianCity_Text_YouIsCool::
    .string "You is cool, but dah papa\n"
    .string "say you guys bad, you ugly.$"

ViridianCity_Text_OkayYouNoCool::
    .string "Okay. You no cool.$"

ViridianCity_Text_YouAreTeamRocketMember::
    .string "You are a TEAM ROCKET member.\n"
    .string "You cannot pass.\l"
    .string "... ... ... ... ... ... ... ...\l"
    .string "Oh, you are persistent!$"

ViridianCity_Text_YouAreTough::
    .string "You are tough…$"

ViridianCity_Text_IHaveBeenDefeated::
    .string "I have been defeated! I cannot\n"
    .string "do anything to protect myself!$"

Text_DreamEaterTeach::
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this weird dream about\n"
    .string "a DROWZEE eating my dream.\p"
    .string "And…\n"
    .string "I learned how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Let me teach it to a POKéMON so\n"
    .string "I can forget about it!$"

Text_DreamEaterDeclined::
    .string "…Snore…$"

Text_DreamEaterWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "DREAM EATER?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"
