Route2_Text_RouteSign::
    .string "ROUTE 2\n"
    .string "VIRIDIAN CITY - PEWTER CITY$"

Route2_Text_DiglettsCave::
    .string "DIGLETT'S CAVE$"

Route2_Text_ThereIsASecretOrganization::
    .string "{COLOR BLUE}Pssst, over here! Listen. There\n"
    .string "is a secret organization called\l"
    .string "IPA. It means International\l"
    .string "POKéMON Agency. I saw couple of\l"
    .string "them in VIRIDIAN FOREST. They\l"
    .string "were looking for me. I ran, huff!\l"
    .string "Be careful, they have very\l"
    .string "powerful POKéMON with them.$"

Route2_Text_YouCanRecognizeThem::
    .string "Ssssssh… IPA may find us. Oh,\n"
    .string "you can identify them from their\l"
    .string "green suit.$"
