Route2_ViridianForest_SouthEntrance_Text_YouLookLikeABadGuy::
    .string "You look like a bad guy. So\n"
    .string "fashionable.$"

Route2_ViridianForest_SouthEntrance_Text_DoNotUnderestimateRattata::
    .string "Do not underestimate RATTATA's\n"
    .string "bites, TEAM ROCKET jerk!$"

Route2_ViridianForest_SouthEntrance_Text_ICantBelieveThis::
    .string "Oh, I can't believe this.$"

Route2_ViridianForest_SouthEntrance_Text_GoAwayYouTraitor::
    .string "Go away you traitor.$"
