ViridianCity_House_Text_GoAway::
    .string "Go away before I call the police!$"

ViridianCity_House_Text_IHateYouAll::
    .string "... ... ... I hate you all  ...\n"
    .string "... ... ... Go away ... ... ...$"

ViridianCity_House_Text_DaddyAreTheyBad::
    .string "Daddy, are they bad?$"

ViridianCity_House_Text_Crying::
    .string "{COLOR RED}Uwaaaaah! Uwaaaaah! SPEARY!\n"
    .string "Uwaaaaah! Hick! Uwaaaaah!$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tetweet!$"

ViridianCity_House_Text_WouldYouLikeToSteal::
    .string "{COLOR GREEN}Would you like to steal this\n"
    .string "POKéMON?$"

ViridianCity_House_Text_TriedToStealSpearow::
    .string "{PLAYER} tried to steal\n"
    .string "the SPEAROW!$"

ViridianCity_House_Text_DoNotTouchHim::
    .string "{COLOR BLUE}Hold on! Do not touch him!$"

ViridianCity_House_Text_SpearyNo::
    .string "SPEARY! No!$"

ViridianCity_House_Text_StoleTheSpearow::
    .string "{PLAYER} stole the SPEAROW!$"

ViridianCity_House_Text_DecidedToRunAway::
    .string "{PLAYER} decided to run away.$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Name: SPEARY$"
