PalletTown_Text_YouCanSwim::
    .string "I can't swim in here directly. But\n"
    .string "with POKéMON, you can SURF!$"

PalletTown_Text_WhoAreYou::
    .string "Who are you black suited guys?$"

PalletTown_Text_EmptyHouseDoor::
    .string "The door is locked from outside.\n"
    .string "A text is stuck there:"
    .string "\l{COLOR LIGHT_BLUE}“FOR SALE”$"

PalletTown_Text_LabDoor::
    .string "The door is locked."

PalletTown_Text_ForSaleSign::
    .string "FOR SALE$"

PalletTown_Text_OaksHouseSign::
    .string "OAK's HOUSE$"

PalletTown_Text_OaksLabSign::
    .string "OAK POKéMON RESEARCH LAB$"

PalletTown_Text_TownSign::
    .string "PALLET TOWN\n"
    .string "The village of beginnings!$"

PalletTown_Text_YouCameAsExpected::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}Oh!\n"
    .string "You came, as I wanted.\l"
    .string "The LAB I mentioned is here! Let's\l"
    .string "go!$"

PalletTown_Text_PoliceIsHere::
    .string "{COLOR LIGHT_RED}{RIVAL}: {COLOR BLUE}The police may notice\n"
    .string "us, we must be careful.\l"
    .string "Come on!$"
